### ISSUE TITLE
sign of force

### ISSUE THREAD

**Issue by poinco-gogo** [andysim/helpme#20]
Dear developers,

Shouldn't the sign of force be opposite to the default one?
The following code describes how I calculated numerical differentiation and compared it to the analytical one.
    
    helpme::Matrix<double> coordsD(
        {{2.0, 2.0, 2.0}, {2.5, 2.0, 3.0}, {1.5, 2.0, 3.0}, {0.0, 0.0, 0.0}, {0.5, 0.0, 1.0}, {-0.5, 0.0, 1.0}});
    helpme::Matrix<double> chargesD({-0.834, 0.417, 0.417, -0.834, 0.417, 0.417});
    double scaleFactorD = 332.0716;

    double energyD = 0;
    helpme::Matrix<double> forcesD(6, 3);
    helpme::Matrix<double> virialD(1, 6);
    helpme::Matrix<double> potentialAndFieldD(6, 4);

    auto pmeD = std::unique_ptr<PMEInstanceD>(new PMEInstanceD);
    pmeD->setup(1, 0.3, 5, 32, 32, 32, scaleFactorD, 1);
    pmeD->setLatticeVectors(20, 20, 20, 90, 90, 90, PMEInstanceD::LatticeType::XAligned);
    // Compute the energy and forces
    energyD = pmeD->computeEFRec(0, chargesD, coordsD, forcesD);

    std::cout << "force_analytical: " << forcesD[0][0] << '\n';

    double alpha = 1e-5;

    coordsD[0][0] += alpha;

    double ene_p = pmeD->computeEFRec(0, chargesD, coordsD, forcesD);

    coordsD[0][0] -= 2. * alpha;

    double ene_m = pmeD->computeEFRec(0, chargesD, coordsD, forcesD);

    double numerical = -(ene_p - ene_m) * 0.5 / alpha;

    std::cout << "force_numerical: " << numerical << '\n';`

The output is::

`force_analytical: 0.603153
force_numerical: -0.603153`

I'm sorry if I have overlooked something.

Best,
Koichi

**Comment by andysim** [comment]
Dear Koichi,

Thank you very much for reaching out about this.  I think you are correct; it looks like I am computing the gradient, not the force.  I will correct the code shortly; this is obviously very important for dynamics.  Thankfully the code is still young so the change will not affect too many people I hope.  If you have any suggestions for or problems with the code, please feel free to reach out.

Best regards,

Andy.
